server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/order-service
    username: root
    password: rahulvj17
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:9296

#eureka:
  #instance:
    #prefer-ip-address: true
  #client:
   #fetch-registry: true
    #register-with-eureka: true
    #serviceUrl:
      #defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
